from fisite.top.api.rest.TmallSelectedItemsSearchRequest import TmallSelectedItemsSearchRequest
from fisite.top.api.rest.TaobaokeItemsCouponGetRequest import TaobaokeItemsCouponGetRequest
from fisite.top.api.rest.TmallItemsDiscountSearchRequest import TmallItemsDiscountSearchRequest
from fisite.top.api.rest.TaobaokeListurlGetRequest import TaobaokeListurlGetRequest
from fisite.top.api.rest.AreasGetRequest import AreasGetRequest
from fisite.top.api.rest.FeedbackAddRequest import FeedbackAddRequest
from fisite.top.api.rest.TaobaokeCaturlGetRequest import TaobaokeCaturlGetRequest
from fisite.top.api.rest.ItemsListGetRequest import ItemsListGetRequest
from fisite.top.api.rest.TmallTemaiItemsSearchRequest import TmallTemaiItemsSearchRequest
from fisite.top.api.rest.ShoprecommendShopsGetRequest import ShoprecommendShopsGetRequest
from fisite.top.api.rest.ItempropvaluesGetRequest import ItempropvaluesGetRequest
from fisite.top.api.rest.UmpPromotionGetRequest import UmpPromotionGetRequest
from fisite.top.api.rest.TaobaokeItemsRelateGetRequest import TaobaokeItemsRelateGetRequest
from fisite.top.api.rest.ItemGetRequest import ItemGetRequest
from fisite.top.api.rest.TaobaokeWidgetShopsConvertRequest import TaobaokeWidgetShopsConvertRequest
from fisite.top.api.rest.ShoprecommendItemsGetRequest import ShoprecommendItemsGetRequest
from fisite.top.api.rest.WidgetAppapiruleCheckRequest import WidgetAppapiruleCheckRequest
from fisite.top.api.rest.TaobaokeItemsGetRequest import TaobaokeItemsGetRequest
from fisite.top.api.rest.TopatsResultGetRequest import TopatsResultGetRequest
from fisite.top.api.rest.ItempropsGetRequest import ItempropsGetRequest
from fisite.top.api.rest.ShopGetRequest import ShopGetRequest
from fisite.top.api.rest.TimeGetRequest import TimeGetRequest
from fisite.top.api.rest.CategoryrecommendItemsGetRequest import CategoryrecommendItemsGetRequest
from fisite.top.api.rest.ItemrecommendItemsGetRequest import ItemrecommendItemsGetRequest
from fisite.top.api.rest.TaobaokeWidgetItemsConvertRequest import TaobaokeWidgetItemsConvertRequest
from fisite.top.api.rest.TaobaokeWidgetUrlConvertRequest import TaobaokeWidgetUrlConvertRequest
from fisite.top.api.rest.TaobaokeReportGetRequest import TaobaokeReportGetRequest
from fisite.top.api.rest.TaobaokeShopsGetRequest import TaobaokeShopsGetRequest
from fisite.top.api.rest.TaobaokeItemsDetailGetRequest import TaobaokeItemsDetailGetRequest
from fisite.top.api.rest.KfcKeywordSearchRequest import KfcKeywordSearchRequest
from fisite.top.api.rest.WidgetLoginstatusGetRequest import WidgetLoginstatusGetRequest
from fisite.top.api.rest.TmallTemaiSubcatsSearchRequest import TmallTemaiSubcatsSearchRequest
from fisite.top.api.rest.UserBuyerGetRequest import UserBuyerGetRequest
from fisite.top.api.rest.TaobaokeShopsRelateGetRequest import TaobaokeShopsRelateGetRequest
from fisite.top.api.rest.UserrecommendItemsGetRequest import UserrecommendItemsGetRequest
from fisite.top.api.rest.SellercatsListGetRequest import SellercatsListGetRequest
from fisite.top.api.rest.ItemSkuGetRequest import ItemSkuGetRequest
from fisite.top.api.rest.ShopcatsListGetRequest import ShopcatsListGetRequest
from fisite.top.api.rest.ItemSkusGetRequest import ItemSkusGetRequest
from fisite.top.api.rest.ItemcatsGetRequest import ItemcatsGetRequest
